name: Container Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - uses: depot/setup-action@v1
      - uses: depot/build-push-action@v1
        with:
          project: 6mczp3kf9v
          context: container
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/sampsyo/cs3410-infra:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{GITHUB_REPOSITORY}}
            org.opencontainers.image.description=RISC-V tooling for CS 3410
